use crate::compiler::ast::{Program, Stmt, Expr, Pattern, TemplatePart};

pub struct KotlinTranspiler {
    indent_level: usize,
}

impl KotlinTranspiler {
    pub fn new() -> Self {
        Self { indent_level: 0 }
    }

    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }

    pub fn transpile(&mut self, program: &Program) -> Result<String, String> {
        let mut top_level_stmts = Vec::new();
        let mut functions = Vec::new();

        for stmt in &program.stmts {
            match stmt {
                Stmt::Fun { .. } => functions.push(stmt),
                _ => top_level_stmts.push(stmt),
            }
        }

        let mut out = String::new();
        out.push_str("// Auto-generated by Aly Kotlin Transpiler\n");
        out.push_str("package aly.generated\n\n");
        out.push_str("import java.util.*\n\n");
        out.push_str("class AlyApp {\n");
        self.indent_level = 1;

        // Generate functions as member methods
        for fun in functions {
            out.push_str(&self.transpile_stmt(fun)?);
            out.push_str("\n");
        }

        // Generate the run/main method
        out.push_str(&format!("{}fun run() {{\n", self.indent()));
        self.indent_level += 1;
        for stmt in top_level_stmts {
            out.push_str(&self.transpile_stmt(stmt)?);
        }
        self.indent_level -= 1;
        out.push_str(&format!("{}}}\n\n", self.indent()));

        // Companion object with JVM entry point
        out.push_str(&format!("{}companion object {{\n", self.indent()));
        self.indent_level += 1;
        out.push_str(&format!("{}@JvmStatic\n", self.indent()));
        out.push_str(&format!("{}fun main(args: Array<String>) {{\n", self.indent()));
        self.indent_level += 1;
        out.push_str(&format!("{}AlyApp().run()\n", self.indent()));
        self.indent_level -= 1;
        out.push_str(&format!("{}}}\n", self.indent()));
        self.indent_level -= 1;
        out.push_str(&format!("{}}}\n", self.indent()));

        self.indent_level = 0;
        out.push_str("}\n");

        Ok(out)
    }

    fn transpile_stmt(&mut self, stmt: &Stmt) -> Result<String, String> {
        let mut out = String::new();
        match stmt {
            Stmt::Let { name, init, .. } => {
                out.push_str(&format!("{}var {}", self.indent(), name));
                if let Some(expr) = init {
                    out.push_str(&format!(": Any? = {}", self.transpile_expr(expr)?));
                } else {
                    out.push_str(": Any? = null");
                }
                out.push_str("\n");
            }
            Stmt::Const { name, init, .. } => {
                out.push_str(&format!("{}val {}: Any? = {}\n", self.indent(), name, self.transpile_expr(init)?));
            }
            Stmt::Assign { target, value } => {
                out.push_str(&format!("{}{} = {}\n", self.indent(), self.transpile_expr(target)?, self.transpile_expr(value)?));
            }
            Stmt::Expr(expr) => {
                out.push_str(&format!("{}{}\n", self.indent(), self.transpile_expr(expr)?));
            }
            Stmt::Return(expr_opt) => {
                if let Some(expr) = expr_opt {
                    out.push_str(&format!("{}return {}\n", self.indent(), self.transpile_expr(expr)?));
                } else {
                    out.push_str(&format!("{}return null\n", self.indent()));
                }
            }
            Stmt::Break => {
                out.push_str(&format!("{}break\n", self.indent()));
            }
            Stmt::Continue => {
                out.push_str(&format!("{}continue\n", self.indent()));
            }
            Stmt::Throw(expr) => {
                out.push_str(&format!("{}throw Exception(({}).toString())\n", self.indent(), self.transpile_expr(expr)?));
            }
            Stmt::Try { body, catch_var, catch_body, finally_body } => {
                out.push_str(&format!("{}try {{\n", self.indent()));
                self.indent_level += 1;
                for s in body {
                    out.push_str(&self.transpile_stmt(s)?);
                }
                self.indent_level -= 1;
                out.push_str(&format!("{}}} catch ({} : Exception) {{\n", self.indent(), catch_var.as_deref().unwrap_or("e")));
                self.indent_level += 1;
                for s in catch_body {
                    out.push_str(&self.transpile_stmt(s)?);
                }
                self.indent_level -= 1;
                if !finally_body.is_empty() {
                    out.push_str(&format!("{}}} finally {{\n", self.indent()));
                    self.indent_level += 1;
                    for s in finally_body {
                        out.push_str(&self.transpile_stmt(s)?);
                    }
                    self.indent_level -= 1;
                }
                out.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::If { condition, then_body, elifs, else_body } => {
                out.push_str(&format!("{}if ({}) {{\n", self.indent(), self.transpile_expr(condition)?));
                self.indent_level += 1;
                for s in then_body {
                    out.push_str(&self.transpile_stmt(s)?);
                }
                self.indent_level -= 1;
                for (elif_cond, elif_body) in elifs {
                    out.push_str(&format!("{}}} else if ({}) {{\n", self.indent(), self.transpile_expr(elif_cond)?));
                    self.indent_level += 1;
                    for s in elif_body {
                        out.push_str(&self.transpile_stmt(s)?);
                    }
                    self.indent_level -= 1;
                }
                if let Some(el_body) = else_body {
                    out.push_str(&format!("{}}} else {{\n", self.indent()));
                    self.indent_level += 1;
                    for s in el_body {
                        out.push_str(&self.transpile_stmt(s)?);
                    }
                    self.indent_level -= 1;
                }
                out.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::While { condition, body } => {
                out.push_str(&format!("{}while ({}) {{\n", self.indent(), self.transpile_expr(condition)?));
                self.indent_level += 1;
                for s in body {
                    out.push_str(&self.transpile_stmt(s)?);
                }
                self.indent_level -= 1;
                out.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::For { init, condition, update, body } => {
                out.push_str(&format!("{}{{\n", self.indent()));
                self.indent_level += 1;
                if let Some(i) = init {
                    out.push_str(&self.transpile_stmt(i)?);
                }
                let cond_str = if let Some(c) = condition {
                    self.transpile_expr(c)?
                } else {
                    "true".to_string()
                };
                out.push_str(&format!("{}while ({}) {{\n", self.indent(), cond_str));
                self.indent_level += 1;
                for s in body {
                    out.push_str(&self.transpile_stmt(s)?);
                }
                if let Some(u) = update {
                    out.push_str(&format!("{}{}\n", self.indent(), self.transpile_expr(u)?));
                }
                self.indent_level -= 1;
                out.push_str(&format!("{}}}\n", self.indent()));
                self.indent_level -= 1;
                out.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::DoWhile { body, condition } => {
                out.push_str(&format!("{}do {{\n", self.indent()));
                self.indent_level += 1;
                for s in body {
                    out.push_str(&self.transpile_stmt(s)?);
                }
                self.indent_level -= 1;
                out.push_str(&format!("{}}} while ({})\n", self.indent(), self.transpile_expr(condition)?));
            }
            Stmt::Foreach { item, collection, body } => {
                out.push_str(&format!("{}for ({} in ({}) as Iterable<*>) {{\n", self.indent(), item, self.transpile_expr(collection)?));
                self.indent_level += 1;
                for s in body {
                    out.push_str(&self.transpile_stmt(s)?);
                }
                self.indent_level -= 1;
                out.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::Fun { name, params, body, .. } => {
                let params_str = params.iter()
                    .map(|p| format!("{}: Any?", p))
                    .collect::<Vec<_>>()
                    .join(", ");
                out.push_str(&format!("{}fun {}({}): Any? {{\n", self.indent(), name, params_str));
                self.indent_level += 1;
                for s in body {
                    out.push_str(&self.transpile_stmt(s)?);
                }
                out.push_str(&format!("{}return null\n", self.indent()));
                self.indent_level -= 1;
                out.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::Match { scrutinee, arms } => {
                out.push_str(&format!("{}when ({}) {{\n", self.indent(), self.transpile_expr(scrutinee)?));
                self.indent_level += 1;
                for arm in arms {
                    let mut patterns_str = Vec::new();
                    for pat in &arm.patterns {
                        match pat {
                            Pattern::Literal(expr) => patterns_str.push(self.transpile_expr(expr)?),
                            Pattern::Range(start, end) => patterns_str.push(format!("in {}..{}", self.transpile_expr(start)?, self.transpile_expr(end)?)),
                            Pattern::Wildcard => patterns_str.push("else".to_string()),
                            Pattern::Or(exprs) => {
                                let mut parts = Vec::new();
                                for e in exprs {
                                    parts.push(self.transpile_expr(e)?);
                                }
                                patterns_str.push(parts.join(", "));
                            }
                        }
                    }
                    out.push_str(&format!("{}{} -> {{\n", self.indent(), patterns_str.join(", ")));
                    self.indent_level += 1;
                    for s in &arm.body {
                        out.push_str(&self.transpile_stmt(s)?);
                    }
                    self.indent_level -= 1;
                    out.push_str(&format!("{}}}\n", self.indent()));
                }
                self.indent_level -= 1;
                out.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::Destructure { names, init, .. } => {
                let temp_name = format!("_destruct_{}", names.join("_"));
                out.push_str(&format!("{}val {} = ({}) as List<*>\n", self.indent(), temp_name, self.transpile_expr(init)?));
                for (idx, name) in names.iter().enumerate() {
                    out.push_str(&format!("{}var {} = {}[{}]\n", self.indent(), name, temp_name, idx));
                }
            }
            Stmt::Lazy { name, init } => {
                out.push_str(&format!("{}val {} by lazy {{ {} }}\n", self.indent(), name, self.transpile_expr(init)?));
            }
            Stmt::MacroDef { .. } => {
                out.push_str(&format!("{}// macro definition omitted in transpilation\n", self.indent()));
            }
            Stmt::Coroutine { name, body, .. } => {
                out.push_str(&format!("{}fun {}() {{ /* coroutine stub */ }}\n", self.indent(), name));
            }
            Stmt::Yield(expr_opt) => {
                if let Some(expr) = expr_opt {
                    out.push_str(&format!("{}// yield {}\n", self.indent(), self.transpile_expr(expr)?));
                } else {
                    out.push_str(&format!("{}// yield\n", self.indent()));
                }
            }
        }
        Ok(out)
    }

    fn transpile_expr(&self, expr: &Expr) -> Result<String, String> {
        match expr {
            Expr::Int(val) => Ok(val.to_string()),
            Expr::Float(val) => Ok(val.to_string()),
            Expr::Char(val) => Ok(format!("'{}'", val)),
            Expr::Str(val) => {
                let escaped = val.replace("\"", "\\\"").replace("\n", "\\n");
                Ok(format!("\"{}\"", escaped))
            }
            Expr::Bool(val) => Ok(val.to_string()),
            Expr::None => Ok("null".to_string()),
            Expr::Void => Ok("Unit".to_string()),
            Expr::Var(name) => Ok(name.clone()),
            Expr::TemplateStr(parts) => {
                let mut out = String::from("\"");
                for part in parts {
                    match part {
                        TemplatePart::Text(t) => out.push_str(&t.replace("\"", "\\\"")),
                        TemplatePart::Var(v) => out.push_str(&format!("${{{}}}", v)),
                    }
                }
                out.push_str("\"");
                Ok(out)
            }
            Expr::UnaryOp { op, expr } => {
                let op_kotlin = match op.as_str() {
                    "not" => "!",
                    _ => op.as_str(),
                };
                Ok(format!("({}{})", op_kotlin, self.transpile_expr(expr)?))
            }
            Expr::BinOp { left, op, right } => {
                let op_kotlin = match op.as_str() {
                    "and" => "&&",
                    "or" => "||",
                    "xor" => "^",
                    "eq" => "==",
                    "neq" => "!=",
                    "lt" => "<",
                    "lte" => "<=",
                    "gt" => ">",
                    "gte" => ">=",
                    _ => op.as_str(),
                };
                Ok(format!("(({}) {} ({}))", self.transpile_expr(left)?, op_kotlin, self.transpile_expr(right)?))
            }
            Expr::Call { function, args } => {
                let mut args_str = Vec::new();
                for a in args {
                    args_str.push(self.transpile_expr(a)?);
                }
                Ok(format!("{}({})", self.transpile_expr(function)?, args_str.join(", ")))
            }
            Expr::Index { object, index } => {
                Ok(format!("{}[{}]", self.transpile_expr(object)?, self.transpile_expr(index)?))
            }
            Expr::PropAccess { object, prop } => {
                Ok(format!("{}.{}", self.transpile_expr(object)?, prop))
            }
            Expr::Array(exprs) => {
                let mut parts = Vec::new();
                for e in exprs {
                    parts.push(self.transpile_expr(e)?);
                }
                Ok(format!("listOf({})", parts.join(", ")))
            }
            Expr::Tuple(exprs) => {
                let mut parts = Vec::new();
                for e in exprs {
                    parts.push(self.transpile_expr(e)?);
                }
                Ok(format!("listOf({})", parts.join(", ")))
            }
            Expr::Object(fields) => {
                let mut parts = Vec::new();
                for (k, v) in fields {
                    parts.push(format!("\"{}\" to {}", k, self.transpile_expr(v)?));
                }
                Ok(format!("mapOf({})", parts.join(", ")))
            }
            Expr::Percent(expr) => {
                Ok(format!("(({}) / 100.0)", self.transpile_expr(expr)?))
            }
            Expr::AnonymousFun { params, body, .. } => {
                let params_str = params.join(", ");
                let mut body_str = String::new();
                for s in body {
                    body_str.push_str(&self.transpile_stmt_inline(s)?);
                }
                Ok(format!("{{ {} -> {} }}", params_str, body_str))
            }
            Expr::MacroExpand { name, args } => {
                let mut args_str = Vec::new();
                for a in args {
                    args_str.push(self.transpile_expr(a)?);
                }
                Ok(format!("{}_macro({})", name, args_str.join(", ")))
            }
            Expr::YieldExpr(expr) => {
                Ok(format!("/* yield */ {}", self.transpile_expr(expr)?))
            }
        }
    }

    fn transpile_stmt_inline(&self, stmt: &Stmt) -> Result<String, String> {
        let mut transpiler = KotlinTranspiler { indent_level: 0 };
        let mut s = transpiler.transpile_stmt(stmt)?;
        s = s.trim().to_string();
        Ok(s)
    }
}
